_BASE_: ../Base-bagtricks.yml

# added some stuff for eval but rest is equivalent

MODEL:

  DEVICE: cuda:0

  META_ARCHITECTURE: BaselineUAL

  HEADS:
    NAME: BayesHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: GlobalAvgPool
    NECK_FEAT: before
    CLS_LAYER: Linear
    #TEST_TIME_ENS: 30 # hardcoded

  LOSSES:
    NAME: ("TripletLoss", "DataUncertaintyLoss")

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: True
      SCALE: 1.

    DUL:
      EPSILON: 0.1
      LAMBDA: 1.
      SCALE: 1.


DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  METRIC: cosine
  EXTRA_END_EVAL: True
  EXTRA_END_EVAL_METRIC: [cosine, sigma_cosine, sqrt_sigma_cosine, euclidean, sigma_euclidean, sqrt_sigma_euclidean, kl_divergence, js_divergence, bhat_distance, wasserstein]
  EVAL_PERIOD: 5

OUTPUT_DIR: /results_nas/ange8547/hiwi/UAL/orig

KEEP_ONLY_BEST_CHECKPOINT: True