MODEL:
  META_ARCHITECTURE: Baseline_DNet

  BACKBONE:
    NAME: build_resnet_DNet_backbone
    NORM: BN
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN_PATH: ยง/results_nas/ange8547/DNet/resnet_v1_50_targetmarket_standard_AC1/imagenet_init

  HEADS:
    NAME: EmbeddingHead_DNet_pretrain
    NORM: BN
    POOL_LAYER: GlobalAvgPool
    NUM_CLASSES: 751

  LOSSES:
    NAME: ("CrossEntropyLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.
    
  PIXEL_MEAN: [123.68, 116.78, 103.94]
  PIXEL_STD: [1, 1, 1]

  DEVICE: cuda:0

DATASETS: # is updated in tool script
  NAMES: ("MarketDNet",)
  TESTS: ("MarketDNet",)

OUTPUT_DIR: /results_nas/ange8547/DNet/fastreid # is updated in tool script

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  INTERPOLATION_MODE: 2

  FLIP:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 1

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 149
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 32

  SCHED: MultiStepLR
  STEPS: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148]
  GAMMA: 0.95

  WARMUP_ITERS: 0

  CHECKPOINT_PERIOD: 25

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 100
  METRIC: euclidean_dnet

CUDNN_BENCHMARK: True
